### ISSUE TITLE
planning demo can not start planning path

### ISSUE THREAD

**Issue by hankerbit** [czjaixuexi/carla_ros_bridge_pnc#2]
Hi, thanks for sharing the demo code. 
What are the parameters in "controller_config.yaml" to get good performance. Can you share them?

**Comment by czjaixuexi** [comment]
Hello, the parameters in the "controller_config.yaml" file in the current repository are the ones I adjusted and they work well based on the scenario in "controller_demo.launch". The map used is "Town05" and the vehicle speed is 8m/s. If you want to try other scenarios, here are my suggestions for adjustments:
For "LQR", you can adjust "Q_ed" to speed up or slow down the convergence of lateral error, and adjust "Q_ephi" to speed up or slow down the convergence of heading angle error. Increasing the "R_value" will make the system more stable but slower in response, while decreasing the "R_value" will make the response faster but the system may become unstable.
For "PurePursuit", increasing "k_pure" will increase the lookahead distance and improve system stability, but it will also increase the steady-state error and exhibit early turn-in phenomena.
For "Stanley", increasing "k_cte" will accelerate the convergence of lateral error but may cause system instability.

**Comment by hankerbit** [comment]
> Hello, the parameters in the "controller_config.yaml" file in the current repository are the ones I adjusted and they work well based on the scenario in "controller_demo.launch". The map used is "Town05" and the vehicle speed is 8m/s. If you want to try other scenarios, here are my suggestions for adjustments: For "LQR", you can adjust "Q_ed" to speed up or slow down the convergence of lateral error, and adjust "Q_ephi" to speed up or slow down the convergence of heading angle error. Increasing the "R_value" will make the system more stable but slower in response, while decreasing the "R_value" will make the response faster but the system may become unstable. For "PurePursuit", increasing "k_pure" will increase the lookahead distance and improve system stability, but it will also increase the steady-state error and exhibit early turn-in phenomena. For "Stanley", increasing "k_cte" will accelerate the convergence of lateral error but may cause system instability.

It is detail information, thanks, I will try.
