### ISSUE TITLE
Does the vehicle parameters match the car model in carla?

### ISSUE THREAD

**Issue by leaves369** [czjaixuexi/carla_ros_bridge_pnc#4]
Hi, thanks for your sharing!
     I notice that there are  vehicle parameters in ControllerNode, i wonder that does these params match the vehicle model in carla or do you define by yourself?

**Comment by czjaixuexi** [comment]
I haven't found the specific model parameters for the vehicles in CARLA, so I just defined approximate values.

**Comment by leaves369** [comment]
Thanks a lot!

**Comment by leaves369** [comment]
I notice that maybe we are all Chinese, is it convenient to have your wechat?  Thank a lot!

**Comment by czjaixuexi** [comment]
> I notice that maybe we are all Chinese, is it convenient to have your wechat? Thank a lot!

412445762
