### ISSUE TITLE
Avoid_and_Follow_1 file not exist

### ISSUE THREAD

**Issue by Liuzy0908** [czjaixuexi/carla_ros_bridge_pnc#5]
Hi, this is a great and amazing work!  

When I run `python scenario_runner.py --scenario Avoid_and_Follow_1 --waitForEgo`, I found that there are no `Avoid_and_Follow_1 ` files in [scenario_runner repo](https://github.com/carla-simulator/scenario_runner), and if running other scenario files, some errors will be reported. 

Could you provide the `Avoid_and_Follow_1` scenario file? Thanks very much!

**Comment by czjaixuexi** [comment]
> Hi, this is a great and amazing work!
> 
> When I run `python scenario_runner.py --scenario Avoid_and_Follow_1 --waitForEgo`, I found that there are no `Avoid_and_Follow_1 ` files in [scenario_runner repo](https://github.com/carla-simulator/scenario_runner), and if running other scenario files, some errors will be reported.
> 
> Could you provide the `Avoid_and_Follow_1` scenario file? Thanks very much!
I have uploaded the code containing this scenario in this repository"https://github.com/czjaixuexi/scenario_runner/tree/v0.9.11-czj".

**Comment by czjaixuexi** [comment]
I have uploaded the code containing this scenario in this repository"https://github.com/czjaixuexi/scenario_runner/tree/v0.9.11-czj".

**Comment by Liuzy0908** [comment]
thank you for your efforts!

> I have uploaded the code containing this scenario in this repository"https://github.com/czjaixuexi/scenario_runner/tree/v0.9.11-czj".
